{% set name = "tranquilizer" %}
{% set version = "0.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a9c25f9d8e1a672ed3142c8b60636ca20c0826af397eafe5d2e2413aba303a00

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vv
  entry_points:
    - tranquilizer = tranquilizer.main:run
  skip: True # [py<36 or py>=313]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - flask
    - werkzeug >=0.15, <2.1
    - flask-restx
    - python-dateutil
    - flask-cors
    - flask-jwt-extended >=4

test:
  requires:
    - pip
  imports:
    - tranquilizer
  commands:
    - tranquilizer --help
    - pip check

about:
  home: https://github.com/ContinuumIO/tranquilizer
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Put your Python functions to REST
  description: |
    Deploy a REST API with one line by decorating your functions.
  dev_url: https://github.com/ContinuumIO/tranquilizer
  doc_url: https://github.com/ContinuumIO/tranquilizer?tab=readme-ov-file#readme

extra:
  recipe-maintainers:
    - AlbertDeFusco
